[package]
name = "atcoder"
version = "0.1.0"
edition = "2021"
default-run = "main"

[workspace]
# cargo ... -p mylib
members = ["mylib"]

[dependencies]
mylib = { path = "mylib" }

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "katex.html",
]
