[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = "0.4"
itertools = "0.10"
num = "0.4"
superslice = "1.0"

ac-library-rs = "0.1.1"
once_cell = "1.19"

rand = "0.8"

# petgraph = "0.6"
