[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = "0.4"
itertools = "0.10"
superslice = "1.0"
num-integer = "0.1"
# num-traits = "0.2"
ac-library-rs = "0.1.1"
once_cell = "1.19"

colored = "2.0"
rand = "0.8"

# petgraph = "0.6"
